import { sidebar } from "vuepress-theme-hope";

export const enSidebar = sidebar({
  "/": [
    "",
    {
      text: "How to Use",
      icon: "creative",
      prefix: "demo/",
      link: "demo/",
      children: "structure",
    },
    {
      text: "Categories",
      icon: "note",
      children: [
        { text: "Programming", icon: "code", link: "/programming/" },
        { text: "JavaScript", icon: "javascript", link: "/programming/javascript/" },
        { text: "TypeScript", icon: "typescript", link: "/programming/typescript/" },
        { text: "Framework", icon: "layers", link: "/programming/framework/" },
        { text: "DevOps", icon: "tool", link: "/programming/devops/" },
        { text: "Operating Systems", icon: "linux", link: "/os/" },
        { text: "Networking", icon: "network", link: "/network/" },
        { text: "Database", icon: "database", link: "/database/" },
        { text: "SQL", icon: "code", link: "/database/sql/" },
        { text: "MySQL", icon: "mysql", link: "/database/mysql/" },
        { text: "MongoDB", icon: "mongodb", link: "/database/mongodb/" },
        { text: "Algorithms", icon: "algorithm", link: "/algorithms/" },
        { text: "DSA", icon: "structure", link: "/dsa/" },
        { text: "Architecture", icon: "diagram", link: "/programming/architechture/" },
        { text: "Interview", icon: "question", link: "/interview/" },
        { text: "Projects", icon: "project", link: "/project/" },
      ],
    },
    {
      text: "Software Tutorials",
      icon: "software",
      prefix: "tutorial/",
      link: "tutorial/",
    },
    {
      text: "Blog",
      icon: "blog",
      prefix: "blog/",
      link: "blog/",
    },
    {
      text: "Site Collection",
      icon: "sitemap",
      prefix: "site",
      link: "site/",
      children: "structure",
    },
    {
      text: "Essays",
      icon: "flower",
      prefix: "private/",
      children: "structure",
    },
    {
      text: "About",
      icon: "info",
      prefix: "about/",
      link: "about",
    },
  ],
  "/programming/": "structure",
  "/programming/javascript/": "structure",
  "/programming/typescript/": "structure",
  "/programming/framework/": "structure",
  "/programming/devops/": "structure",
  "/os/": "structure",
  "/os/process-thread/": "structure",
  "/os/scheduling/": "structure",
  "/os/memory/": "structure",
  "/os/ipc/": "structure",
  "/os/io-filesystem/": "structure",
  "/os/filesystem/": "structure",
  "/os/security/": "structure",
  "/os/kernel-security/": "structure",
  "/os/virtualization-distributed/": "structure",
  "/network/": "structure",
  "/network/tcp-udp/": "structure",
  "/network/ip-nat/": "structure",
  "/network/dns/": "structure",
  "/network/http-https/": "structure",
  "/network/tls-websocket/": "structure",
  "/network/rest-api/": "structure",
  "/network/load-balancing-cdn/": "structure",
  "/network/routing-congestion/": "structure",
  "/database/": "structure",
  "/database/sql/": "structure",
  "/database/mysql/": "structure",
  "/database/mongodb/": "structure",
  "/algorithms/": "structure",
  "/dsa/": "structure",
  "/programming/architechture/": "structure",
  "/interview/": "structure",
  "/project/": "structure",
  "/site/": "structure",
  "/blog": "structure",
  "/tutorial": "structure",
});
