name: Triển khai tài liệu

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Thiết lập Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm

      - name: Cài đặt phụ thuộc
        run: pnpm install --frozen-lockfile

      - name: Xây dựng tài liệu
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |
          pnpm build
          touch src/.vuepress/dist/.nojekyll

      - name: Triển khai tài liệu
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: src/.vuepress/dist
          token: ${{ secrets.GITHUB_TOKEN }}